server:
  port: 8080
  servlet:
    context-path: /ptit-exam

spring:
  application:
    name: PTIT-Exam
  security:
    user:
      name: root
      password: admin
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/ptit-exam"
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  logging:
    level.org.hibernate:
      SQL: DEBUG
      Type: TRACE
  mail:
    host: smtp.gmail.com
    port: 587
    username: cloneacc20k@gmail.com
    password: tihf ysge zxsh ukyn
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
